name: stat18
channels:
  - defaults
dependencies:
  - python=3.6.3
  - pip=10.0.1
  - pip:
    - numpy==1.13.1
    - matplotlib==2.1.0
    - pandas==0.20.3
    - seaborn==0.8
    - scikit-learn==0.19.1
    - statsmodels==0.9.0
    - ipykernel==4.8.2
    - ipython==6.1.0
    - SQLAlchemy==1.1.13
    - xlrd==1.1.0 #added by Jeppe (to use pandas method read_excel -> necessary in old env)
    - plotly==2.7.0
